#!/usr/bin/env node
// SessionStart hook: mount the skills the ACTIVE packs require. Each pack
// declares the skills it needs (`skills` in its pack.mjs); this hook derives
// the union over the packs declared in .claudinite-checks.json (no pack is
// active by default — bootstrap seeds `basics`, which carries the baseline
// skills) and (re)generates the `.claude/skills/<name>` symlinks to match —
// created, retargeted, and removed as the declarations change, so the mounted
// set always tracks the packs and nothing is ever committed (a committed link
// dangles on any plain checkout, where the gitignored corpus is absent — see
// gha/pages-artifact-symlinks). A generated, self-ignoring
// `.claude/skills/.gitignore` keeps the mounts out of git status. Entries this
// hook doesn't own — a project's own skills, links pointing elsewhere — are
// never touched. Fails soft: a broken mount must never block a session.
// Registered per-repo, after whatever populates the corpus — see bootstrap.md.
import {
  existsSync, mkdirSync, readdirSync, lstatSync, readlinkSync, readFileSync,
  writeFileSync, symlinkSync, unlinkSync,
} from 'node:fs';
import { join, dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

try {
  const skillsDir = dirname(fileURLToPath(import.meta.url)); // <corpus>/skills
  const corpusRoot = dirname(skillsDir);
  const projectRoot = process.env.CLAUDE_PROJECT_DIR || process.cwd();

  let declared = [];
  const configPath = join(projectRoot, '.claudinite-checks.json');
  if (existsSync(configPath)) {
    const raw = JSON.parse(readFileSync(configPath, 'utf8'));
    if (Array.isArray(raw.packs)) declared = raw.packs;
  }

  const { loadPacks, isActive } = await import(join(corpusRoot, 'packs', 'registry.mjs'));
  // Include the project's own local packs — a local pack can require a canon
  // skill AND bundle its own under <pack>/skills/, mounted from the tracked pack
  // dir rather than the corpus mount.
  const packs = await loadPacks({ localRoot: projectRoot });
  const localPacksRoot = join(projectRoot, '.claudinite', 'local_packs');

  // The union over the active packs, each skill resolved to its SOURCE directory:
  // a local pack's own bundled skill (<pack>/skills/<name>) if it has one, else
  // the canon skills tree. A required-but-missing skill is the skill-ownership
  // check's finding to report, not this hook's reason to break. Canon packs sort
  // before local ones, so a name shared with a canon skill resolves to canon.
  const active = packs.filter((p) => isActive(p, { packs: declared }));
  const sourceByName = new Map();
  for (const pack of active) {
    for (const name of pack.skills ?? []) {
      if (sourceByName.has(name)) continue;
      let source = null;
      if (pack.local) {
        const bundled = join(pack.dir, 'skills', name);
        if (existsSync(join(bundled, 'SKILL.md'))) source = bundled;
      }
      if (!source) {
        const canon = join(skillsDir, name);
        if (existsSync(join(canon, 'SKILL.md'))) source = canon;
      }
      if (source) sourceByName.set(name, source);
    }
  }
  const wanted = [...sourceByName.keys()].sort();

  const mountDir = join(projectRoot, '.claude', 'skills');
  if (!wanted.length && !existsSync(mountDir)) process.exit(0);
  mkdirSync(mountDir, { recursive: true });

  const lstatOrNull = (p) => { try { return lstatSync(p); } catch { return null; } };
  // A mount is ours iff it is a symlink into the corpus's skills/ tree OR into
  // the project's own local_packs (a local pack's bundled skill) — lexical
  // resolve, so a dangling leftover still matches and gets cleaned.
  const owned = (entry) => {
    const st = lstatOrNull(join(mountDir, entry));
    if (!st || !st.isSymbolicLink()) return false;
    const target = resolve(mountDir, readlinkSync(join(mountDir, entry)));
    return target.startsWith(skillsDir + sep) || target.startsWith(localPacksRoot + sep);
  };

  for (const entry of readdirSync(mountDir)) {
    if (entry !== '.gitignore' && owned(entry) && !wanted.includes(entry)) {
      unlinkSync(join(mountDir, entry));
    }
  }

  const mounted = [];
  for (const name of wanted) {
    const link = join(mountDir, name);
    const target = relative(mountDir, sourceByName.get(name));
    if (lstatOrNull(link)) {
      if (!owned(name)) continue; // the project's own entry wins — never overwrite
      if (readlinkSync(link) === target) { mounted.push(name); continue; }
      unlinkSync(link); // ours, but stale target (corpus/pack moved) — retarget
    }
    symlinkSync(target, link);
    mounted.push(name);
  }

  const gitignorePath = join(mountDir, '.gitignore');
  const gitignore = [
    '# GENERATED by Claudinite (skills/mount-skills.mjs) — the skill mounts the',
    '# active packs require, regenerated every session start. Not tracked.',
    '.gitignore',
    ...mounted,
  ].join('\n') + '\n';
  if (!lstatOrNull(gitignorePath) || readFileSync(gitignorePath, 'utf8') !== gitignore) {
    writeFileSync(gitignorePath, gitignore);
  }
} catch {
  // fail soft — a broken mount must never block a session
}
